### ISSUE TITLE
help to build 

### ISSUE THREAD

**Issue by ig-amt1** [4nh3k/zmk-config#2]
hey bro, I decided to make this board (td34) because the design and the low cost attract me a lot, however, I didn't understand how I would add it to the ZMK installation list, I'm still quite a newbie, if you can help me I'd appreciate it a lot

**Comment by 4nh3k** [comment]
Hello there, I'm not suggest you to not build td34 as a newbie because it my first design board and have a lot of issues(short of gnd and sda on right side, not having an on/off switch), maybe comeback later. But if you already print this board out let me know.

**Comment by ig-amt1** [comment]
I already made the print order, in a few days it will arrive at my house, by the way, do you have photos of it ready? I got curious

**Comment by ig-amt1** [comment]
I already have sweep v2.1, technically it wouldn't be my first keyboard

**Comment by 4nh3k** [comment]
if u already print it out, u can contact me via discord (pussycat#5909).
